/datum/round_event_control/antagonist/solo/stowaway
	name = "Stowaway"
	roundstart = TRUE

	antag_flag = ROLE_STOWAWAY
	antag_datum = /datum/antagonist/stowaway
	weight = 25
	min_players = 10

	maximum_antags_global = 1
	denominator = 25
	tags = list(TAG_LOW, TAG_MINORANTAG)

	protected_roles = list(
	JOB_CAPTAIN,
	JOB_HEAD_OF_PERSONNEL,
	JOB_HEAD_OF_SECURITY,
	JOB_RESEARCH_DIRECTOR,
	JOB_CHIEF_ENGINEER,
	JOB_CHIEF_MEDICAL_OFFICER,
	JOB_BRIDGE_ASSISTANT,
	JOB_VETERAN_ADVISOR,
	//Silicon
	JOB_AI,
	JOB_CYBORG,
	JOB_SECURITY_CYBORG,
	JOB_PERSONAL_AI,
	JOB_HUMAN_AI,
	//Security
	JOB_WARDEN,
	JOB_DETECTIVE,
	JOB_SECURITY_OFFICER,
	JOB_SECURITY_OFFICER_MEDICAL,
	JOB_SECURITY_OFFICER_ENGINEERING,
	JOB_SECURITY_OFFICER_SCIENCE,
	JOB_SECURITY_OFFICER_SUPPLY,
	JOB_CORRECTIONS_OFFICER,
	//Engineering
	JOB_STATION_ENGINEER,
	JOB_ATMOSPHERIC_TECHNICIAN,
	JOB_ENGINEERING_GUARD,
	JOB_TELECOMMS_SPECIALIST,
	//Medical
	JOB_CORONER,
	JOB_MEDICAL_DOCTOR,
	JOB_PARAMEDIC,
	JOB_CHEMIST,
	JOB_ORDERLY,
	//Science
	JOB_SCIENTIST,
	JOB_ROBOTICIST,
	JOB_GENETICIST,
	JOB_SCIENCE_GUARD,
	//Supply
	JOB_QUARTERMASTER,
	JOB_CARGO_TECHNICIAN,
	JOB_CARGO_GORILLA,
	JOB_SHAFT_MINER,
	JOB_BITRUNNER,
	JOB_CUSTOMS_AGENT,
	//Service
	JOB_BARTENDER,
	JOB_BOTANIST,
	JOB_COOK,
	JOB_CHEF,
	JOB_JANITOR,
	JOB_CLOWN,
	JOB_MIME,
	JOB_CURATOR,
	JOB_LAWYER,
	JOB_CHAPLAIN,
	JOB_PSYCHOLOGIST,
	JOB_BARBER,
	JOB_BOUNCER,
	JOB_PUN_PUN,
	//CentCom
	JOB_CENTCOM,
	JOB_CENTCOM_OFFICIAL,
	JOB_CENTCOM_ADMIRAL,
	JOB_CENTCOM_COMMANDER,
	JOB_CENTCOM_VIP,
	JOB_CENTCOM_BARTENDER,
	JOB_CENTCOM_CUSTODIAN,
	JOB_CENTCOM_THUNDERDOME_OVERSEER,
	JOB_CENTCOM_MEDICAL_DOCTOR,
	JOB_CENTCOM_RESEARCH_OFFICER,
	JOB_CENTCOM_SPECIAL_OFFICER,
	JOB_CENTCOM_PRIVATE_SECURITY,
	JOB_BLUESHIELD,
	JOB_NT_REP,
	)


