/obj/item/storage/part_replacer/bluespace/tier5/PopulateContents()
	for(var/i in 1 to 10)
		new /obj/item/stock_parts/capacitor/giga(src)
		new /obj/item/stock_parts/scanning_module/unilatera(src)
		new /obj/item/stock_parts/servo/atto(src)
		new /obj/item/stock_parts/micro_laser/super_quadultra(src)
		new /obj/item/stock_parts/matter_bin/dark_matter(src)
		new /obj/item/stock_parts/power_store/cell/vortex(src)
